"""initial tables

Revision ID: 6b08277c2c7a
Revises: 
Create Date: 2026-05-20 21:43:57.231241

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6b08277c2c7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_string', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_string')
    )
    op.create_index('ix_geocode_cache_query_string', 'geocode_cache', ['query_string'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('certification_details', sa.JSON(), nullable=True),
    sa.Column('capacity_value', sa.Float(), nullable=True),
    sa.Column('capacity_unit', sa.String(length=50), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppliers_category', 'suppliers', ['category'], unique=False)
    op.create_index('ix_suppliers_country', 'suppliers', ['country'], unique=False)
    op.create_index('ix_suppliers_is_active', 'suppliers', ['is_active'], unique=False)
    op.create_index('ix_suppliers_name', 'suppliers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'procurement_manager', 'analyst', name='userrole'), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('parsed_constraints', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='querystatus'), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_queries_created_at', 'queries', ['created_at'], unique=False)
    op.create_index('ix_queries_status', 'queries', ['status'], unique=False)
    op.create_index('ix_queries_user_id', 'queries', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('output_snapshot', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_agent_name', 'audit_logs', ['agent_name'], unique=False)
    op.create_index('ix_audit_logs_query_id', 'audit_logs', ['query_id'], unique=False)
    op.create_table('query_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('constraint_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('proximity_score', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('compliance_matrix', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_results_query_id', 'query_results', ['query_id'], unique=False)
    op.create_index('ix_query_results_rank', 'query_results', ['query_id', 'rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_query_results_rank', table_name='query_results')
    op.drop_index('ix_query_results_query_id', table_name='query_results')
    op.drop_table('query_results')
    op.drop_index('ix_audit_logs_query_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_agent_name', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_queries_user_id', table_name='queries')
    op.drop_index('ix_queries_status', table_name='queries')
    op.drop_index('ix_queries_created_at', table_name='queries')
    op.drop_table('queries')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_suppliers_name', table_name='suppliers')
    op.drop_index('ix_suppliers_is_active', table_name='suppliers')
    op.drop_index('ix_suppliers_country', table_name='suppliers')
    op.drop_index('ix_suppliers_category', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_geocode_cache_query_string', table_name='geocode_cache')
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###