"""production v2 tier status citations scope evaluator

Revision ID: 8fb55de4fa16
Revises: a96b78f8e3d4
Create Date: 2026-05-26 10:56:05.073151

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8fb55de4fa16'
down_revision: Union[str, None] = 'a96b78f8e3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create user_supplier_saves table (Tier 2 junction table)
    op.create_table('user_supplier_saves',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('supplier_id', sa.UUID(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_supplier_saves_user', 'user_supplier_saves', ['user_id'], unique=False)
    op.create_index('ix_user_supplier_saves_unique', 'user_supplier_saves', ['user_id', 'supplier_id'], unique=True)

    op.add_column('queries', sa.Column('search_scope', sa.String(length=20), nullable=False, server_default='approved_only'))
    op.add_column('queries', sa.Column('evaluator_retries', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('queries', sa.Column('evaluator_verdict', sa.Text(), nullable=True))

    # Create the enum type FIRST, then use it in the column
    supplierstatus_enum = sa.Enum('approved', 'saved', 'discovered', 'rejected', name='supplierstatus')
    supplierstatus_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('suppliers', sa.Column('status', supplierstatus_enum, nullable=False, server_default='approved'))
    op.add_column('suppliers', sa.Column('source_url', sa.String(length=1000), nullable=True))
    op.add_column('suppliers', sa.Column('source_citations', sa.JSON(), nullable=True))
    op.add_column('suppliers', sa.Column('approved_by_user_id', sa.UUID(), nullable=True))
    op.add_column('suppliers', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_suppliers_status'), 'suppliers', ['status'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'users', ['approved_by_user_id'], ['id'])

    # Backfill: classify existing suppliers by their source
    op.execute(
        "UPDATE suppliers SET status = 'approved' "
        "WHERE source = 'manual' OR source IS NULL"
    )
    op.execute(
        "UPDATE suppliers SET status = 'discovered' "
        "WHERE source = 'web_discovery'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_status'), table_name='suppliers')
    op.drop_column('suppliers', 'approved_at')
    op.drop_column('suppliers', 'approved_by_user_id')
    op.drop_column('suppliers', 'source_citations')
    op.drop_column('suppliers', 'source_url')
    op.drop_column('suppliers', 'status')
    op.drop_column('queries', 'evaluator_verdict')
    op.drop_column('queries', 'evaluator_retries')
    op.drop_column('queries', 'search_scope')
    op.drop_index('ix_user_supplier_saves_unique', table_name='user_supplier_saves')
    op.drop_index('ix_user_supplier_saves_user', table_name='user_supplier_saves')
    op.drop_table('user_supplier_saves')
    sa.Enum('approved', 'saved', 'discovered', 'rejected', name='supplierstatus').drop(op.get_bind())
    # ### end Alembic commands ###