"""add_supplier_source_column

Revision ID: a96b78f8e3d4
Revises: 6b08277c2c7a
Create Date: 2026-05-24 19:55:28.389859

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a96b78f8e3d4'
down_revision: Union[str, None] = '6b08277c2c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'source')
    # ### end Alembic commands ###